export const skills = [
  "Semantic & accessiable HTML",
  "Error handling",
  "Git",
  "Responsive Web Design",
  "React",
  "GitHub Pull Requests & Review",
  // eslint-disable-next-line no-script-url
  "JavaScript language: ESC6+",
  "React Hooks",
  "NPM",
  "Working width API (fetch, axios)",
  "Redux (Toolkit)",
  "Immutability",
  "Promises, Async/Await",
  "Redux-Saga",
  "Markdown",
  "Debugging", 
  "React Router",
  "Scrum",
  "CSS Flexbox",
  "CSS Grid",
  "Trello",
  "Teamwork",
  "CSS BEM convention",
];

export const testSkills = [
  "Java language",
  "Jira",
  "SQL language",
  "Docker",
  "Postman",
  "SoapUI",
  "Selenium WebDriver",
  "Selenium + BDD",
  "Selenium Grid",
  "Selenium IDE",
  "Linux System",
  "Xpath and CSS",
  "TDD",
  "BDD",
  "POST",
  "HTTP",
  "SEO",
  "GET",
  "Performance tests",
  "Relational databases"
];

export const nextSkills = [
  "JS classes",
  "Information Security",
  "Automation testing",
  "Data Visualization",
  "Back End development and APIs",
  "Node.js",
  "TypeScript",
  "Cypress",
  "React Context",
];
